---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    options:
      memory: 4096
      cpus: 2

# lint:
#   name: yamllint
platforms:
  # - name: trusty
  #   box: ubuntu/trusty64
  #   # interfaces:
  #   #   - network_name: public_network
  #   #     type: dhcp
  #   #     auto_config: true    
  - name: web
    box: ubuntu/bionic64
    memory: 4096
    cpus: 2
#    instance_raw_config_args:
#      - "vm.network 'forwarded_port', guest: 80, host: 8880"
#      - "vm.network 'forwarded_port', guest: 443, host: 8443"
    interfaces:
       - network_name: private_network
         type: static
         ip: 192.168.63.1
         auto_config: true
# UNCOMMENT FOR LOCAL DEBUGGING, CHECK WITH  https://www.vagrantup.com/docs/networking/public_network.html
       - network_name: public_network
         type: dhcp
         bridge: "wlp4s0"
#         ip: 192.168.2.22
#         auto_config: true
  #- name: bionic
  #  box: ubuntu/bionic64
    # interfaces:
    #   - network_name: public_network
    #     type: dhcp
    #     auto_config: true
  # - name: centos6
  #   box: centos/6    
  #- name: centos7
  #  box: centos/7
  # - name: fedora28
  #   box: generic/fedora28
  # - name: alpine
  #   box: generic/alpine28

    
provisioner:
  name: ansible
  env:
    ENVIRONMENT: molecule
    BOX_PROVIDER: molecule
    ANSIBLE_ROLES_PATH: "${PWD}/provisioners/shared/roles:${PWD}/provisioners/shared/roles_custom:roles"
  # lint:
  #   name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
